version: "3.6"

services:
    web:
        build: ./docker
        ports:
            - "80:80"
        volumes:
            - ./:/siteroot
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: user_micro_service
            MYSQL_USER: service_root
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
    test-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: user_micro_service_testing
            MYSQL_USER: service_root
            MYSQL_PASSWORD: password
volumes:
    dbdata:
